# .github/workflows/ci.yml

name: Earthly +main

on:
  push:
    branches:
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15
    - uses: actions/checkout@v4
    - name: Run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: EARTHLY_SECRETS="remote=https://x-access-token:${GITHUB_TOKEN}@github.com/SapphicCode/fork-beets" earthly --ci --push +main
