# .github/workflows/ci.yml

name: Earthly +main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15
    - uses: actions/checkout@v4
    - name: Run build
      run: earthly --ci --push +main
